### ISSUE TITLE
S'inspirer de l'ordre des ingénieurs américain et de l'iron ring canadien ?

### ISSUE THREAD

**Issue by mmai** [ordre-des-developpeurs/odd-constitution#13]
https://en.m.wikipedia.org/wiki/Iron_Ring

https://en.m.wikipedia.org/wiki/Order_of_the_Engineer

http://www.theatlantic.com/technology/archive/2015/11/programmers-should-not-call-themselves-engineers/414271/

**Comment by kryzaal** [comment]
Je ne pense pas que l'on puisse importer du mythos de nulle part. L'Histoire française sur le sujet est assez riche pour nous permettre de trouver nos propres repères.

**Comment by BodySplash** [comment]
Effectivement ceux sont des sources intéressantes. C'est vrai que la question de fond c'est de savoir si la métaphore de l'ingénierie s'applique réellement à ce que nous faisons. 

Je trouve ces articles d'Alistair Cockburn assez intéressants sur le sujet : 
http://alistair.cockburn.us/The+end+of+software+engineering+and+the+start+of+economic-cooperative+gaming
http://alistair.cockburn.us/Foundations+for+Software+Engineering

De manière générale, je ne sais jamais quoi penser des cérémonies, des serments, etc. Certaines sources disent que ça a réellement un impact, d'autres que c'est devenu du decorum sans signification particulière.

**Comment by Squallygator** [comment]
Je sais que ce n'est pas le sujet mais personnellement, j'ai déjà une alliance, et ça me suffit.
SVP, pas de dress code, de tatouage ou autre bijou, l'ordre doit pouvoir accepter autant Gandalf, Brice de Nice que Howard Stark avec tout au plus une carte d'Avengers dans la poche, s'il en faut une...
Toute autre référence plus adaptée peut aussi servir

**Comment by mmai** [comment]
Je suis d'accord sur le coté kitch d'un cérémonial, j'ai mis les deux premiers liens juste pour le fun. Le vrai sujet est dans l'article de theatlantic qui soulève une des problématiques autour de laquelle nous tournons : comment imprimer l'éthique dans notre activité ?

**Comment by kryzaal** [comment]
Par une règlementation interne, votée par les développeurs eux-mêmes. Ensuite on en revient au besoin d'instances judiciaires et exécutives, inévitables selon moi si l'on veut qu'un ordre serve à quelque chose.

**Comment by BodySplash** [comment]
Fermeture pour le moment pour faire un peu de ménage. Peut être qu'on follow up serait de constituer une bibliographie de ressources intéressantes, ou à étudier en groupe.
