### ISSUE TITLE
Quel serais le nom idéal ?

### ISSUE THREAD

**Issue by BodySplash** [ordre-des-developpeurs/odd-constitution#8]
ordre guilde ou autre ?
développeuses et développeurs ou de ceux qui développent ?

**Comment by JeffLeFoll** [comment]
Mon avis:
Guilde c'est un peut désuet, je ne sais pas si c'est toujours utilisé ?
Ordre, c'est clair et ça parle à tous le monde.

Sinon en alternative il y a aussi le terme collège (Collèges des Magistrats, Collège des Psychologues...).

Des professionnels du développement ?

**Comment by kryzaal** [comment]
Je suis d'avis de partir sur Ordre des développeurs pour le moment, quitte à faire voter ça une fois la chose lancée.
Le nom doit être percutant pour le moment, on verra plus tard pour faire quelque chose de consensuel.

Des développeurs, car dans l'idée initiale, cela devait inclure les étudiants et les retraités, avec un pouvoir moindre.

**Comment by josselinauguste** [comment]
kryzaal +1

**Comment by BodySplash** [comment]
Je fais un peu de vide dans les issues. On va dire que celle ci pour le moment est considérée comme réglée :)
